# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64d0eea39d72979810c291236637635de41601a3fb4df9497005e1bc02e05be81233080809ad2c72137fca1d548f85c0d32a0047caadb50683022cb6d1c2be17

test:
  secret_key_base: 7865096ebaebccdc864490b31d22c7df7e8e967abcdba40f7442f6ba5d65b4f85f0115907bd1a9a491f9333dd1bd810a6eb30b6c3e4d1d8779e80449cc9dc396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
